"""Language-neutral scenario model shared by every engine harness.

A scenario is one personnel record plus the corpus-wide as-of date. Each engine
harness materializes the same scenario into its own input format (fixed-width
master file, database rows, Java objects) and emits the same normalized result
rows, so the engines can be compared directly.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
CORPUS_PATH = REPO_ROOT / "tests" / "corpus" / "scenarios.yaml"
GOLDEN_DIR = REPO_ROOT / "tests" / "golden"

DENY_REASONS = ("STAT", "ADVM", "TIG", "TIS", "DRIL")


@dataclass
class Scenario:
    """One MARINE_MASTER record.

    Dates are ``YYYYMMDD`` integers; ``0`` means the field is not populated,
    which is how the fixed-width feed represents an absent date.
    """

    id: str
    note: str
    edipi: int
    grade: str
    grade_num: int
    dt_last_promo: int
    pebd: int
    dt_enlist: int
    dt_orig_promo: int = 0
    grade_eff_dt: int = 0
    last_nm: str = "TESTCASE"
    first_nm: str = "SCENARIO"
    middle_init: str = "X"
    pmos: str = "0311"
    red_in_grade_ind: str = "N"
    brk_svc_mos: int = 0
    adv_matl_ind: str = "N"
    adv_matl_mos: int = 0
    duty_stat: str = "AC"
    component: str = "A"
    rc_drill_stat: str = " "
    tags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class Corpus:
    as_of: dt.date
    scenarios: list[Scenario]

    @property
    def as_of_yyyymmdd(self) -> int:
        return int(self.as_of.strftime("%Y%m%d"))

    def by_id(self, scenario_id: str) -> Scenario:
        for s in self.scenarios:
            if s.id == scenario_id:
                return s
        raise KeyError(scenario_id)


def load_corpus(path: Optional[Path] = None) -> Corpus:
    raw = yaml.safe_load((path or CORPUS_PATH).read_text())
    as_of = raw["as_of"]
    if isinstance(as_of, str):
        as_of = dt.date.fromisoformat(as_of)
    return Corpus(as_of=as_of, scenarios=[Scenario(**s) for s in raw["scenarios"]])


def dump_corpus(corpus: Corpus, path: Optional[Path] = None) -> None:
    payload = {
        "as_of": corpus.as_of.isoformat(),
        "scenarios": [s.to_dict() for s in corpus.scenarios],
    }
    target = path or CORPUS_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "# Generated by tests/corpus/build_corpus.py -- do not edit by hand.\n"
        + yaml.safe_dump(payload, sort_keys=False, width=100)
    )


def to_date(yyyymmdd: int) -> Optional[dt.date]:
    if not yyyymmdd:
        return None
    s = str(yyyymmdd).zfill(8)
    return dt.date(int(s[0:4]), int(s[4:6]), int(s[6:8]))


def shift_months(base: dt.date, months: int, day: Optional[int] = None) -> dt.date:
    """Return ``base`` moved by ``months``, clamping the day to the month length."""
    total = base.year * 12 + (base.month - 1) + months
    year, month = divmod(total, 12)
    month += 1
    target_day = day if day is not None else base.day
    last_day = (dt.date(year + (month == 12), (month % 12) + 1, 1) - dt.timedelta(days=1)).day
    return dt.date(year, month, min(target_day, last_day))


def as_yyyymmdd(value: dt.date) -> int:
    return int(value.strftime("%Y%m%d"))
